### ISSUE TITLE
BNR Prolog

### ISSUE THREAD

**Issue by jchharris** [ridgeworks/clpBNR_pl#1]
Hi,

I used to work on BNR Prolog up to its last release in Nortel circa 1999. I have some experience I can share.

**Comment by ridgeworks** [comment]
Hi Jason,

Good to hear from you. This particular project is an attempt to recreate the CLP component of BNRP (with some help from Bill). 

I've also created an archive of some of the design notes and external papers related to BNRP at:
https://github.com/ridgeworks/BNRProlog-Papers <https://github.com/ridgeworks/BNRProlog-Papers>

If you'd like to participate/contribute we should find a way continue this discussion outside this github issue.


Rick W.

**Comment by StMesh** [comment]
I tested the Mac system in the late 80's at BNR Richardson, and I've done a lot of industry (telecom network design) applications using similar techniques in the last 30 years (most recently in SWI Prolog).   Also worked with Ken Bowen of ALS Prolog on (testing) its port.   If there is anything I can do to help, let me know.

Jonathan

**Comment by ridgeworks** [comment]
Jonathon,

Thanks for the offer. Here's some suggestions of how you can participate, but I'm open to any thoughts you have.

As you may have seen, the intent of this project is to re-create the CLP component of BNRP (the relational interval arithmetic piece) entirely in Prolog as a package that can be run on SWI Prolog. The hope is that this will target the widest possible audience while avoiding all the low level and platform dependant implementation issues. Given you have some experience with SWIP, one thing you could do to help is just download and use it (e.g., try examples in ReadMe) and feedback any issues and suggestions that arise. 

I've also been going through the old BNR material looking for relevant (and practical, i.e., not N Queens) applications that can be used as tutorial level material in the guide (see link from ReadMe). The next example I'm working on is timing analysis of digital circuits. If you have anything in your experience you think would fit the mold, I'd like to hear about it. 

At some point the guide needs a reference chapter which should probably mimic the style (not necessarily the presentation) of the SWIP documentation. 

I'm intrigued by this technology because it seems to have almost magical properties when there's a fit with a problem, yet it doesn't seem to have gained much attention. I suspect part of the reason is a disconnect with people (engineers) that actually have the problems which is why I'm trying to focus on the practical side, rather than the academic, but it's probably not the whole story. (Prolog itself seems to be stuck in its own niche.) Any ideas/opinions in this vein would also be welcome.

Rick
